/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.github.vonrosen.quantlib;

public class CalibrationHelperBase {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CalibrationHelperBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CalibrationHelperBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_CalibrationHelperBase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_CalibrationHelperBase __deref__() {
    long cPtr = QuantLibJNI.CalibrationHelperBase___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_CalibrationHelperBase(cPtr, false);
  }

  public boolean isNull() {
    return QuantLibJNI.CalibrationHelperBase_isNull(swigCPtr, this);
  }

  public CalibrationHelperBase() {
    this(QuantLibJNI.new_CalibrationHelperBase(), true);
  }

  public double calibrationError() {
    return QuantLibJNI.CalibrationHelperBase_calibrationError(swigCPtr, this);
  }

}
