/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.github.vonrosen.quantlib;

public class SWIGTYPE_p_Claim {
  private transient long swigCPtr;

  protected SWIGTYPE_p_Claim(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_Claim() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_Claim obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

