/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class BermudanExercise extends Exercise {
  private transient long swigCPtr;

  protected BermudanExercise(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.BermudanExercise_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BermudanExercise obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_BermudanExercise(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BermudanExercise(DateVector dates, boolean payoffAtExpiry) {
    this(QuantLibJNI.new_BermudanExercise__SWIG_0(DateVector.getCPtr(dates), dates, payoffAtExpiry), true);
  }

  public BermudanExercise(DateVector dates) {
    this(QuantLibJNI.new_BermudanExercise__SWIG_1(DateVector.getCPtr(dates), dates), true);
  }

}
