/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class ContinuousAveragingAsianOption extends Instrument {
  private transient long swigCPtr;

  protected ContinuousAveragingAsianOption(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.ContinuousAveragingAsianOption_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ContinuousAveragingAsianOption obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_ContinuousAveragingAsianOption(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ContinuousAveragingAsianOption(Average.Type averageType, Payoff payoff, Exercise exercise) {
    this(QuantLibJNI.new_ContinuousAveragingAsianOption(averageType.swigValue(), Payoff.getCPtr(payoff), payoff, Exercise.getCPtr(exercise), exercise), true);
  }

  public double delta() {
    return QuantLibJNI.ContinuousAveragingAsianOption_delta(swigCPtr, this);
  }

  public double gamma() {
    return QuantLibJNI.ContinuousAveragingAsianOption_gamma(swigCPtr, this);
  }

  public double theta() {
    return QuantLibJNI.ContinuousAveragingAsianOption_theta(swigCPtr, this);
  }

  public double thetaPerDay() {
    return QuantLibJNI.ContinuousAveragingAsianOption_thetaPerDay(swigCPtr, this);
  }

  public double vega() {
    return QuantLibJNI.ContinuousAveragingAsianOption_vega(swigCPtr, this);
  }

  public double rho() {
    return QuantLibJNI.ContinuousAveragingAsianOption_rho(swigCPtr, this);
  }

  public double dividendRho() {
    return QuantLibJNI.ContinuousAveragingAsianOption_dividendRho(swigCPtr, this);
  }

  public double strikeSensitivity() {
    return QuantLibJNI.ContinuousAveragingAsianOption_strikeSensitivity(swigCPtr, this);
  }

}
