/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class ContinuousArithmeticAsianLevyEngine extends PricingEngine {
  private transient long swigCPtr;

  protected ContinuousArithmeticAsianLevyEngine(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.ContinuousArithmeticAsianLevyEngine_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ContinuousArithmeticAsianLevyEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_ContinuousArithmeticAsianLevyEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ContinuousArithmeticAsianLevyEngine(GeneralizedBlackScholesProcess process, QuoteHandle runningAverage, Date startDate) {
    this(QuantLibJNI.new_ContinuousArithmeticAsianLevyEngine(GeneralizedBlackScholesProcess.getCPtr(process), process, QuoteHandle.getCPtr(runningAverage), runningAverage, Date.getCPtr(startDate), startDate), true);
  }

}
