/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class DiscountingSwapEngine extends PricingEngine {
  private transient long swigCPtr;

  protected DiscountingSwapEngine(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.DiscountingSwapEngine_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DiscountingSwapEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_DiscountingSwapEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DiscountingSwapEngine(YieldTermStructureHandle discountCurve, Date settlementDate, Date npvDate) {
    this(QuantLibJNI.new_DiscountingSwapEngine__SWIG_0(YieldTermStructureHandle.getCPtr(discountCurve), discountCurve, Date.getCPtr(settlementDate), settlementDate, Date.getCPtr(npvDate), npvDate), true);
  }

  public DiscountingSwapEngine(YieldTermStructureHandle discountCurve, Date settlementDate) {
    this(QuantLibJNI.new_DiscountingSwapEngine__SWIG_1(YieldTermStructureHandle.getCPtr(discountCurve), discountCurve, Date.getCPtr(settlementDate), settlementDate), true);
  }

  public DiscountingSwapEngine(YieldTermStructureHandle discountCurve) {
    this(QuantLibJNI.new_DiscountingSwapEngine__SWIG_2(YieldTermStructureHandle.getCPtr(discountCurve), discountCurve), true);
  }

  public DiscountingSwapEngine(YieldTermStructureHandle discountCurve, boolean includeSettlementDateFlows, Date settlementDate, Date npvDate) {
    this(QuantLibJNI.new_DiscountingSwapEngine__SWIG_3(YieldTermStructureHandle.getCPtr(discountCurve), discountCurve, includeSettlementDateFlows, Date.getCPtr(settlementDate), settlementDate, Date.getCPtr(npvDate), npvDate), true);
  }

  public DiscountingSwapEngine(YieldTermStructureHandle discountCurve, boolean includeSettlementDateFlows, Date settlementDate) {
    this(QuantLibJNI.new_DiscountingSwapEngine__SWIG_4(YieldTermStructureHandle.getCPtr(discountCurve), discountCurve, includeSettlementDateFlows, Date.getCPtr(settlementDate), settlementDate), true);
  }

  public DiscountingSwapEngine(YieldTermStructureHandle discountCurve, boolean includeSettlementDateFlows) {
    this(QuantLibJNI.new_DiscountingSwapEngine__SWIG_5(YieldTermStructureHandle.getCPtr(discountCurve), discountCurve, includeSettlementDateFlows), true);
  }

}
