/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class DMinus extends TridiagonalOperator {
  private transient long swigCPtr;

  protected DMinus(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.DMinus_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DMinus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_DMinus(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DMinus(long gridPoints, double h) {
    this(QuantLibJNI.new_DMinus(gridPoints, h), true);
  }

}
