/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class FlatForward extends YieldTermStructure {
  private transient long swigCPtr;

  protected FlatForward(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.FlatForward_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FlatForward obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_FlatForward(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FlatForward(Date referenceDate, QuoteHandle forward, DayCounter dayCounter, Compounding compounding, Frequency frequency) {
    this(QuantLibJNI.new_FlatForward__SWIG_0(Date.getCPtr(referenceDate), referenceDate, QuoteHandle.getCPtr(forward), forward, DayCounter.getCPtr(dayCounter), dayCounter, compounding.swigValue(), frequency.swigValue()), true);
  }

  public FlatForward(Date referenceDate, QuoteHandle forward, DayCounter dayCounter, Compounding compounding) {
    this(QuantLibJNI.new_FlatForward__SWIG_1(Date.getCPtr(referenceDate), referenceDate, QuoteHandle.getCPtr(forward), forward, DayCounter.getCPtr(dayCounter), dayCounter, compounding.swigValue()), true);
  }

  public FlatForward(Date referenceDate, QuoteHandle forward, DayCounter dayCounter) {
    this(QuantLibJNI.new_FlatForward__SWIG_2(Date.getCPtr(referenceDate), referenceDate, QuoteHandle.getCPtr(forward), forward, DayCounter.getCPtr(dayCounter), dayCounter), true);
  }

  public FlatForward(Date referenceDate, double forward, DayCounter dayCounter, Compounding compounding, Frequency frequency) {
    this(QuantLibJNI.new_FlatForward__SWIG_3(Date.getCPtr(referenceDate), referenceDate, forward, DayCounter.getCPtr(dayCounter), dayCounter, compounding.swigValue(), frequency.swigValue()), true);
  }

  public FlatForward(Date referenceDate, double forward, DayCounter dayCounter, Compounding compounding) {
    this(QuantLibJNI.new_FlatForward__SWIG_4(Date.getCPtr(referenceDate), referenceDate, forward, DayCounter.getCPtr(dayCounter), dayCounter, compounding.swigValue()), true);
  }

  public FlatForward(Date referenceDate, double forward, DayCounter dayCounter) {
    this(QuantLibJNI.new_FlatForward__SWIG_5(Date.getCPtr(referenceDate), referenceDate, forward, DayCounter.getCPtr(dayCounter), dayCounter), true);
  }

  public FlatForward(int settlementDays, Calendar calendar, QuoteHandle forward, DayCounter dayCounter, Compounding compounding, Frequency frequency) {
    this(QuantLibJNI.new_FlatForward__SWIG_6(settlementDays, Calendar.getCPtr(calendar), calendar, QuoteHandle.getCPtr(forward), forward, DayCounter.getCPtr(dayCounter), dayCounter, compounding.swigValue(), frequency.swigValue()), true);
  }

  public FlatForward(int settlementDays, Calendar calendar, QuoteHandle forward, DayCounter dayCounter, Compounding compounding) {
    this(QuantLibJNI.new_FlatForward__SWIG_7(settlementDays, Calendar.getCPtr(calendar), calendar, QuoteHandle.getCPtr(forward), forward, DayCounter.getCPtr(dayCounter), dayCounter, compounding.swigValue()), true);
  }

  public FlatForward(int settlementDays, Calendar calendar, QuoteHandle forward, DayCounter dayCounter) {
    this(QuantLibJNI.new_FlatForward__SWIG_8(settlementDays, Calendar.getCPtr(calendar), calendar, QuoteHandle.getCPtr(forward), forward, DayCounter.getCPtr(dayCounter), dayCounter), true);
  }

  public FlatForward(int settlementDays, Calendar calendar, double forward, DayCounter dayCounter, Compounding compounding, Frequency frequency) {
    this(QuantLibJNI.new_FlatForward__SWIG_9(settlementDays, Calendar.getCPtr(calendar), calendar, forward, DayCounter.getCPtr(dayCounter), dayCounter, compounding.swigValue(), frequency.swigValue()), true);
  }

  public FlatForward(int settlementDays, Calendar calendar, double forward, DayCounter dayCounter, Compounding compounding) {
    this(QuantLibJNI.new_FlatForward__SWIG_10(settlementDays, Calendar.getCPtr(calendar), calendar, forward, DayCounter.getCPtr(dayCounter), dayCounter, compounding.swigValue()), true);
  }

  public FlatForward(int settlementDays, Calendar calendar, double forward, DayCounter dayCounter) {
    this(QuantLibJNI.new_FlatForward__SWIG_11(settlementDays, Calendar.getCPtr(calendar), calendar, forward, DayCounter.getCPtr(dayCounter), dayCounter), true);
  }

}
