/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class GaussianLowDiscrepancySequenceGenerator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GaussianLowDiscrepancySequenceGenerator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GaussianLowDiscrepancySequenceGenerator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_GaussianLowDiscrepancySequenceGenerator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GaussianLowDiscrepancySequenceGenerator(UniformLowDiscrepancySequenceGenerator u) {
    this(QuantLibJNI.new_GaussianLowDiscrepancySequenceGenerator(UniformLowDiscrepancySequenceGenerator.getCPtr(u), u), true);
  }

  public SampleRealVector nextSequence() {
    return new SampleRealVector(QuantLibJNI.GaussianLowDiscrepancySequenceGenerator_nextSequence(swigCPtr, this), false);
  }

  public long dimension() {
    return QuantLibJNI.GaussianLowDiscrepancySequenceGenerator_dimension(swigCPtr, this);
  }

}
