/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class GaussLaguerreIntegration {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GaussLaguerreIntegration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GaussLaguerreIntegration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_GaussLaguerreIntegration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GaussLaguerreIntegration(long n, double s) {
    this(QuantLibJNI.new_GaussLaguerreIntegration__SWIG_0(n, s), true);
  }

  public GaussLaguerreIntegration(long n) {
    this(QuantLibJNI.new_GaussLaguerreIntegration__SWIG_1(n), true);
  }

  public double calculate(UnaryFunctionDelegate f) {
    return QuantLibJNI.GaussLaguerreIntegration_calculate(swigCPtr, this, UnaryFunctionDelegate.getCPtr(f), f);
  }

}
