/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class Germany extends Calendar {
  private transient long swigCPtr;

  protected Germany(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.Germany_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Germany obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_Germany(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Germany(Germany.Market m) {
    this(QuantLibJNI.new_Germany__SWIG_0(m.swigValue()), true);
  }

  public Germany() {
    this(QuantLibJNI.new_Germany__SWIG_1(), true);
  }

  public final static class Market {
    public final static Germany.Market Settlement = new Germany.Market("Settlement");
    public final static Germany.Market FrankfurtStockExchange = new Germany.Market("FrankfurtStockExchange");
    public final static Germany.Market Xetra = new Germany.Market("Xetra");
    public final static Germany.Market Eurex = new Germany.Market("Eurex");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Market swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Market.class + " with value " + swigValue);
    }

    private Market(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Market(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Market(String swigName, Market swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Market[] swigValues = { Settlement, FrankfurtStockExchange, Xetra, Eurex };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
