/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class IncrementalStatistics {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IncrementalStatistics(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IncrementalStatistics obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_IncrementalStatistics(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long samples() {
    return QuantLibJNI.IncrementalStatistics_samples(swigCPtr, this);
  }

  public double weightSum() {
    return QuantLibJNI.IncrementalStatistics_weightSum(swigCPtr, this);
  }

  public double mean() {
    return QuantLibJNI.IncrementalStatistics_mean(swigCPtr, this);
  }

  public double variance() {
    return QuantLibJNI.IncrementalStatistics_variance(swigCPtr, this);
  }

  public double standardDeviation() {
    return QuantLibJNI.IncrementalStatistics_standardDeviation(swigCPtr, this);
  }

  public double errorEstimate() {
    return QuantLibJNI.IncrementalStatistics_errorEstimate(swigCPtr, this);
  }

  public double skewness() {
    return QuantLibJNI.IncrementalStatistics_skewness(swigCPtr, this);
  }

  public double kurtosis() {
    return QuantLibJNI.IncrementalStatistics_kurtosis(swigCPtr, this);
  }

  public double min() {
    return QuantLibJNI.IncrementalStatistics_min(swigCPtr, this);
  }

  public double max() {
    return QuantLibJNI.IncrementalStatistics_max(swigCPtr, this);
  }

  public void reset() {
    QuantLibJNI.IncrementalStatistics_reset(swigCPtr, this);
  }

  public void add(double value, double weight) {
    QuantLibJNI.IncrementalStatistics_add__SWIG_0(swigCPtr, this, value, weight);
  }

  public void add(double value) {
    QuantLibJNI.IncrementalStatistics_add__SWIG_1(swigCPtr, this, value);
  }

  public void add(DoubleVector values) {
    QuantLibJNI.IncrementalStatistics_add__SWIG_2(swigCPtr, this, DoubleVector.getCPtr(values), values);
  }

  public void add(DoubleVector values, DoubleVector weights) {
    QuantLibJNI.IncrementalStatistics_add__SWIG_3(swigCPtr, this, DoubleVector.getCPtr(values), values, DoubleVector.getCPtr(weights), weights);
  }

  public IncrementalStatistics() {
    this(QuantLibJNI.new_IncrementalStatistics(), true);
  }

}
