/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class Leg {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Leg(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Leg obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_Leg(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Leg() {
    this(QuantLibJNI.new_Leg__SWIG_0(), true);
  }

  public Leg(long n) {
    this(QuantLibJNI.new_Leg__SWIG_1(n), true);
  }

  public long size() {
    return QuantLibJNI.Leg_size(swigCPtr, this);
  }

  public long capacity() {
    return QuantLibJNI.Leg_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    QuantLibJNI.Leg_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return QuantLibJNI.Leg_isEmpty(swigCPtr, this);
  }

  public void clear() {
    QuantLibJNI.Leg_clear(swigCPtr, this);
  }

  public void add(CashFlow x) {
    QuantLibJNI.Leg_add(swigCPtr, this, CashFlow.getCPtr(x), x);
  }

  public CashFlow get(int i) {
    return new CashFlow(QuantLibJNI.Leg_get(swigCPtr, this, i), false);
  }

  public void set(int i, CashFlow val) {
    QuantLibJNI.Leg_set(swigCPtr, this, i, CashFlow.getCPtr(val), val);
  }

}
