/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class MCEverestEngine extends PricingEngine {
  private transient long swigCPtr;

  protected MCEverestEngine(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.MCEverestEngine_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MCEverestEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_MCEverestEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MCEverestEngine(StochasticProcessArray process, String traits, long timeSteps, long timeStepsPerYear, boolean brownianBridge, boolean antitheticVariate, int requiredSamples, double requiredTolerance, int maxSamples, int seed) {
    this(QuantLibJNI.new_MCEverestEngine__SWIG_0(StochasticProcessArray.getCPtr(process), process, traits, timeSteps, timeStepsPerYear, brownianBridge, antitheticVariate, requiredSamples, requiredTolerance, maxSamples, seed), true);
  }

  public MCEverestEngine(StochasticProcessArray process, String traits, long timeSteps, long timeStepsPerYear, boolean brownianBridge, boolean antitheticVariate, int requiredSamples, double requiredTolerance, int maxSamples) {
    this(QuantLibJNI.new_MCEverestEngine__SWIG_1(StochasticProcessArray.getCPtr(process), process, traits, timeSteps, timeStepsPerYear, brownianBridge, antitheticVariate, requiredSamples, requiredTolerance, maxSamples), true);
  }

  public MCEverestEngine(StochasticProcessArray process, String traits, long timeSteps, long timeStepsPerYear, boolean brownianBridge, boolean antitheticVariate, int requiredSamples, double requiredTolerance) {
    this(QuantLibJNI.new_MCEverestEngine__SWIG_2(StochasticProcessArray.getCPtr(process), process, traits, timeSteps, timeStepsPerYear, brownianBridge, antitheticVariate, requiredSamples, requiredTolerance), true);
  }

  public MCEverestEngine(StochasticProcessArray process, String traits, long timeSteps, long timeStepsPerYear, boolean brownianBridge, boolean antitheticVariate, int requiredSamples) {
    this(QuantLibJNI.new_MCEverestEngine__SWIG_3(StochasticProcessArray.getCPtr(process), process, traits, timeSteps, timeStepsPerYear, brownianBridge, antitheticVariate, requiredSamples), true);
  }

  public MCEverestEngine(StochasticProcessArray process, String traits, long timeSteps, long timeStepsPerYear, boolean brownianBridge, boolean antitheticVariate) {
    this(QuantLibJNI.new_MCEverestEngine__SWIG_4(StochasticProcessArray.getCPtr(process), process, traits, timeSteps, timeStepsPerYear, brownianBridge, antitheticVariate), true);
  }

  public MCEverestEngine(StochasticProcessArray process, String traits, long timeSteps, long timeStepsPerYear, boolean brownianBridge) {
    this(QuantLibJNI.new_MCEverestEngine__SWIG_5(StochasticProcessArray.getCPtr(process), process, traits, timeSteps, timeStepsPerYear, brownianBridge), true);
  }

  public MCEverestEngine(StochasticProcessArray process, String traits, long timeSteps, long timeStepsPerYear) {
    this(QuantLibJNI.new_MCEverestEngine__SWIG_6(StochasticProcessArray.getCPtr(process), process, traits, timeSteps, timeStepsPerYear), true);
  }

  public MCEverestEngine(StochasticProcessArray process, String traits, long timeSteps) {
    this(QuantLibJNI.new_MCEverestEngine__SWIG_7(StochasticProcessArray.getCPtr(process), process, traits, timeSteps), true);
  }

  public MCEverestEngine(StochasticProcessArray process, String traits) {
    this(QuantLibJNI.new_MCEverestEngine__SWIG_8(StochasticProcessArray.getCPtr(process), process, traits), true);
  }

}
