/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class MultiplicativePriceSeasonalityPtr extends Seasonality {
  private transient long swigCPtr;

  protected MultiplicativePriceSeasonalityPtr(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.MultiplicativePriceSeasonalityPtr_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MultiplicativePriceSeasonalityPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_MultiplicativePriceSeasonalityPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MultiplicativePriceSeasonalityPtr(Date seasonalityBaseDate, Frequency frequency, DoubleVector seasonalityFactors) {
    this(QuantLibJNI.new_MultiplicativePriceSeasonalityPtr(Date.getCPtr(seasonalityBaseDate), seasonalityBaseDate, frequency.swigValue(), DoubleVector.getCPtr(seasonalityFactors), seasonalityFactors), true);
  }

}
