/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class PiecewiseFlatHazardRate extends DefaultProbabilityTermStructure {
  private transient long swigCPtr;

  protected PiecewiseFlatHazardRate(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.PiecewiseFlatHazardRate_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PiecewiseFlatHazardRate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_PiecewiseFlatHazardRate(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PiecewiseFlatHazardRate(Date referenceDate, DefaultProbabilityHelperVector instruments, DayCounter dayCounter, double accuracy, BackwardFlat i) {
    this(QuantLibJNI.new_PiecewiseFlatHazardRate__SWIG_0(Date.getCPtr(referenceDate), referenceDate, DefaultProbabilityHelperVector.getCPtr(instruments), instruments, DayCounter.getCPtr(dayCounter), dayCounter, accuracy, BackwardFlat.getCPtr(i), i), true);
  }

  public PiecewiseFlatHazardRate(Date referenceDate, DefaultProbabilityHelperVector instruments, DayCounter dayCounter, double accuracy) {
    this(QuantLibJNI.new_PiecewiseFlatHazardRate__SWIG_1(Date.getCPtr(referenceDate), referenceDate, DefaultProbabilityHelperVector.getCPtr(instruments), instruments, DayCounter.getCPtr(dayCounter), dayCounter, accuracy), true);
  }

  public PiecewiseFlatHazardRate(Date referenceDate, DefaultProbabilityHelperVector instruments, DayCounter dayCounter) {
    this(QuantLibJNI.new_PiecewiseFlatHazardRate__SWIG_2(Date.getCPtr(referenceDate), referenceDate, DefaultProbabilityHelperVector.getCPtr(instruments), instruments, DayCounter.getCPtr(dayCounter), dayCounter), true);
  }

  public PiecewiseFlatHazardRate(int settlementDays, Calendar calendar, DefaultProbabilityHelperVector instruments, DayCounter dayCounter, double accuracy, BackwardFlat i) {
    this(QuantLibJNI.new_PiecewiseFlatHazardRate__SWIG_3(settlementDays, Calendar.getCPtr(calendar), calendar, DefaultProbabilityHelperVector.getCPtr(instruments), instruments, DayCounter.getCPtr(dayCounter), dayCounter, accuracy, BackwardFlat.getCPtr(i), i), true);
  }

  public PiecewiseFlatHazardRate(int settlementDays, Calendar calendar, DefaultProbabilityHelperVector instruments, DayCounter dayCounter, double accuracy) {
    this(QuantLibJNI.new_PiecewiseFlatHazardRate__SWIG_4(settlementDays, Calendar.getCPtr(calendar), calendar, DefaultProbabilityHelperVector.getCPtr(instruments), instruments, DayCounter.getCPtr(dayCounter), dayCounter, accuracy), true);
  }

  public PiecewiseFlatHazardRate(int settlementDays, Calendar calendar, DefaultProbabilityHelperVector instruments, DayCounter dayCounter) {
    this(QuantLibJNI.new_PiecewiseFlatHazardRate__SWIG_5(settlementDays, Calendar.getCPtr(calendar), calendar, DefaultProbabilityHelperVector.getCPtr(instruments), instruments, DayCounter.getCPtr(dayCounter), dayCounter), true);
  }

  public DateVector dates() {
    return new DateVector(QuantLibJNI.PiecewiseFlatHazardRate_dates(swigCPtr, this), false);
  }

  public DoubleVector times() {
    return new DoubleVector(QuantLibJNI.PiecewiseFlatHazardRate_times(swigCPtr, this), false);
  }

  public NodeVector nodes() {
    return new NodeVector(QuantLibJNI.PiecewiseFlatHazardRate_nodes(swigCPtr, this), true);
  }

}
