/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class Protection {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Protection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Protection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_Protection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Protection() {
    this(QuantLibJNI.new_Protection(), true);
  }

  public final static class Side {
    public final static Protection.Side Buyer = new Protection.Side("Buyer");
    public final static Protection.Side Seller = new Protection.Side("Seller");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Side swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Side.class + " with value " + swigValue);
    }

    private Side(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Side(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Side(String swigName, Side swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Side[] swigValues = { Buyer, Seller };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
