/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class QuoteHandleVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected QuoteHandleVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QuoteHandleVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_QuoteHandleVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public QuoteHandleVector() {
    this(QuantLibJNI.new_QuoteHandleVector__SWIG_0(), true);
  }

  public QuoteHandleVector(long n) {
    this(QuantLibJNI.new_QuoteHandleVector__SWIG_1(n), true);
  }

  public long size() {
    return QuantLibJNI.QuoteHandleVector_size(swigCPtr, this);
  }

  public long capacity() {
    return QuantLibJNI.QuoteHandleVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    QuantLibJNI.QuoteHandleVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return QuantLibJNI.QuoteHandleVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    QuantLibJNI.QuoteHandleVector_clear(swigCPtr, this);
  }

  public void add(QuoteHandle x) {
    QuantLibJNI.QuoteHandleVector_add(swigCPtr, this, QuoteHandle.getCPtr(x), x);
  }

  public QuoteHandle get(int i) {
    return new QuoteHandle(QuantLibJNI.QuoteHandleVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, QuoteHandle val) {
    QuantLibJNI.QuoteHandleVector_set(swigCPtr, this, i, QuoteHandle.getCPtr(val), val);
  }

}
