/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class RateHelperVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RateHelperVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RateHelperVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_RateHelperVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RateHelperVector() {
    this(QuantLibJNI.new_RateHelperVector__SWIG_0(), true);
  }

  public RateHelperVector(long n) {
    this(QuantLibJNI.new_RateHelperVector__SWIG_1(n), true);
  }

  public long size() {
    return QuantLibJNI.RateHelperVector_size(swigCPtr, this);
  }

  public long capacity() {
    return QuantLibJNI.RateHelperVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    QuantLibJNI.RateHelperVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return QuantLibJNI.RateHelperVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    QuantLibJNI.RateHelperVector_clear(swigCPtr, this);
  }

  public void add(RateHelper x) {
    QuantLibJNI.RateHelperVector_add(swigCPtr, this, RateHelper.getCPtr(x), x);
  }

  public RateHelper get(int i) {
    return new RateHelper(QuantLibJNI.RateHelperVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, RateHelper val) {
    QuantLibJNI.RateHelperVector_set(swigCPtr, this, i, RateHelper.getCPtr(val), val);
  }

}
