/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class RelinkableBlackVolTermStructureHandle extends BlackVolTermStructureHandle {
  private transient long swigCPtr;

  protected RelinkableBlackVolTermStructureHandle(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.RelinkableBlackVolTermStructureHandle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RelinkableBlackVolTermStructureHandle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_RelinkableBlackVolTermStructureHandle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RelinkableBlackVolTermStructureHandle(BlackVolTermStructure arg0) {
    this(QuantLibJNI.new_RelinkableBlackVolTermStructureHandle__SWIG_0(BlackVolTermStructure.getCPtr(arg0), arg0), true);
  }

  public RelinkableBlackVolTermStructureHandle() {
    this(QuantLibJNI.new_RelinkableBlackVolTermStructureHandle__SWIG_1(), true);
  }

  public void linkTo(BlackVolTermStructure arg0) {
    QuantLibJNI.RelinkableBlackVolTermStructureHandle_linkTo(swigCPtr, this, BlackVolTermStructure.getCPtr(arg0), arg0);
  }

}
