/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class RelinkableDeltaVolQuoteHandle extends DeltaVolQuoteHandle {
  private transient long swigCPtr;

  protected RelinkableDeltaVolQuoteHandle(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.RelinkableDeltaVolQuoteHandle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RelinkableDeltaVolQuoteHandle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_RelinkableDeltaVolQuoteHandle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RelinkableDeltaVolQuoteHandle(DeltaVolQuote arg0) {
    this(QuantLibJNI.new_RelinkableDeltaVolQuoteHandle__SWIG_0(DeltaVolQuote.getCPtr(arg0), arg0), true);
  }

  public RelinkableDeltaVolQuoteHandle() {
    this(QuantLibJNI.new_RelinkableDeltaVolQuoteHandle__SWIG_1(), true);
  }

  public void linkTo(DeltaVolQuote arg0) {
    QuantLibJNI.RelinkableDeltaVolQuoteHandle_linkTo(swigCPtr, this, DeltaVolQuote.getCPtr(arg0), arg0);
  }

}
