/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

public class RelinkableYieldTermStructureHandle extends YieldTermStructureHandle {
  private transient long swigCPtr;

  protected RelinkableYieldTermStructureHandle(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.RelinkableYieldTermStructureHandle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RelinkableYieldTermStructureHandle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_RelinkableYieldTermStructureHandle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RelinkableYieldTermStructureHandle(YieldTermStructure arg0) {
    this(QuantLibJNI.new_RelinkableYieldTermStructureHandle__SWIG_0(YieldTermStructure.getCPtr(arg0), arg0), true);
  }

  public RelinkableYieldTermStructureHandle() {
    this(QuantLibJNI.new_RelinkableYieldTermStructureHandle__SWIG_1(), true);
  }

  public void linkTo(YieldTermStructure arg0) {
    QuantLibJNI.RelinkableYieldTermStructureHandle_linkTo(swigCPtr, this, YieldTermStructure.getCPtr(arg0), arg0);
  }

}
