/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class UnaryFunction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UnaryFunction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnaryFunction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_UnaryFunction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UnaryFunction(UnaryFunctionDelegate arg0) {
    this(QuantLibJNI.new_UnaryFunction(UnaryFunctionDelegate.getCPtr(arg0), arg0), true);
  }

  public double getValue(double x) {
    return QuantLibJNI.UnaryFunction_getValue(swigCPtr, this, x);
  }

}
