/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class YieldTermStructure {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected YieldTermStructure(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YieldTermStructure obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_YieldTermStructure(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_YieldTermStructure __deref__() {
    long cPtr = QuantLibJNI.YieldTermStructure___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_YieldTermStructure(cPtr, false);
  }

  public boolean isNull() {
    return QuantLibJNI.YieldTermStructure_isNull(swigCPtr, this);
  }

  public Observable asObservable() {
    return new Observable(QuantLibJNI.YieldTermStructure_asObservable(swigCPtr, this), true);
  }

  public YieldTermStructure() {
    this(QuantLibJNI.new_YieldTermStructure(), true);
  }

  public DayCounter dayCounter() {
    return new DayCounter(QuantLibJNI.YieldTermStructure_dayCounter(swigCPtr, this), true);
  }

  public Calendar calendar() {
    return new Calendar(QuantLibJNI.YieldTermStructure_calendar(swigCPtr, this), true);
  }

  public Date referenceDate() {
    return new Date(QuantLibJNI.YieldTermStructure_referenceDate(swigCPtr, this), true);
  }

  public Date maxDate() {
    return new Date(QuantLibJNI.YieldTermStructure_maxDate(swigCPtr, this), true);
  }

  public double maxTime() {
    return QuantLibJNI.YieldTermStructure_maxTime(swigCPtr, this);
  }

  public double discount(Date arg0, boolean extrapolate) {
    return QuantLibJNI.YieldTermStructure_discount__SWIG_0(swigCPtr, this, Date.getCPtr(arg0), arg0, extrapolate);
  }

  public double discount(Date arg0) {
    return QuantLibJNI.YieldTermStructure_discount__SWIG_1(swigCPtr, this, Date.getCPtr(arg0), arg0);
  }

  public double discount(double arg0, boolean extrapolate) {
    return QuantLibJNI.YieldTermStructure_discount__SWIG_2(swigCPtr, this, arg0, extrapolate);
  }

  public double discount(double arg0) {
    return QuantLibJNI.YieldTermStructure_discount__SWIG_3(swigCPtr, this, arg0);
  }

  public InterestRate zeroRate(Date d, DayCounter arg1, Compounding arg2, Frequency f, boolean extrapolate) {
    return new InterestRate(QuantLibJNI.YieldTermStructure_zeroRate__SWIG_0(swigCPtr, this, Date.getCPtr(d), d, DayCounter.getCPtr(arg1), arg1, arg2.swigValue(), f.swigValue(), extrapolate), true);
  }

  public InterestRate zeroRate(Date d, DayCounter arg1, Compounding arg2, Frequency f) {
    return new InterestRate(QuantLibJNI.YieldTermStructure_zeroRate__SWIG_1(swigCPtr, this, Date.getCPtr(d), d, DayCounter.getCPtr(arg1), arg1, arg2.swigValue(), f.swigValue()), true);
  }

  public InterestRate zeroRate(Date d, DayCounter arg1, Compounding arg2) {
    return new InterestRate(QuantLibJNI.YieldTermStructure_zeroRate__SWIG_2(swigCPtr, this, Date.getCPtr(d), d, DayCounter.getCPtr(arg1), arg1, arg2.swigValue()), true);
  }

  public InterestRate zeroRate(double t, Compounding arg1, Frequency f, boolean extrapolate) {
    return new InterestRate(QuantLibJNI.YieldTermStructure_zeroRate__SWIG_3(swigCPtr, this, t, arg1.swigValue(), f.swigValue(), extrapolate), true);
  }

  public InterestRate zeroRate(double t, Compounding arg1, Frequency f) {
    return new InterestRate(QuantLibJNI.YieldTermStructure_zeroRate__SWIG_4(swigCPtr, this, t, arg1.swigValue(), f.swigValue()), true);
  }

  public InterestRate zeroRate(double t, Compounding arg1) {
    return new InterestRate(QuantLibJNI.YieldTermStructure_zeroRate__SWIG_5(swigCPtr, this, t, arg1.swigValue()), true);
  }

  public InterestRate forwardRate(Date d1, Date d2, DayCounter arg2, Compounding arg3, Frequency f, boolean extrapolate) {
    return new InterestRate(QuantLibJNI.YieldTermStructure_forwardRate__SWIG_0(swigCPtr, this, Date.getCPtr(d1), d1, Date.getCPtr(d2), d2, DayCounter.getCPtr(arg2), arg2, arg3.swigValue(), f.swigValue(), extrapolate), true);
  }

  public InterestRate forwardRate(Date d1, Date d2, DayCounter arg2, Compounding arg3, Frequency f) {
    return new InterestRate(QuantLibJNI.YieldTermStructure_forwardRate__SWIG_1(swigCPtr, this, Date.getCPtr(d1), d1, Date.getCPtr(d2), d2, DayCounter.getCPtr(arg2), arg2, arg3.swigValue(), f.swigValue()), true);
  }

  public InterestRate forwardRate(Date d1, Date d2, DayCounter arg2, Compounding arg3) {
    return new InterestRate(QuantLibJNI.YieldTermStructure_forwardRate__SWIG_2(swigCPtr, this, Date.getCPtr(d1), d1, Date.getCPtr(d2), d2, DayCounter.getCPtr(arg2), arg2, arg3.swigValue()), true);
  }

  public InterestRate forwardRate(double t1, double t2, Compounding arg2, Frequency f, boolean extrapolate) {
    return new InterestRate(QuantLibJNI.YieldTermStructure_forwardRate__SWIG_3(swigCPtr, this, t1, t2, arg2.swigValue(), f.swigValue(), extrapolate), true);
  }

  public InterestRate forwardRate(double t1, double t2, Compounding arg2, Frequency f) {
    return new InterestRate(QuantLibJNI.YieldTermStructure_forwardRate__SWIG_4(swigCPtr, this, t1, t2, arg2.swigValue(), f.swigValue()), true);
  }

  public InterestRate forwardRate(double t1, double t2, Compounding arg2) {
    return new InterestRate(QuantLibJNI.YieldTermStructure_forwardRate__SWIG_5(swigCPtr, this, t1, t2, arg2.swigValue()), true);
  }

  public void enableExtrapolation() {
    QuantLibJNI.YieldTermStructure_enableExtrapolation(swigCPtr, this);
  }

  public void disableExtrapolation() {
    QuantLibJNI.YieldTermStructure_disableExtrapolation(swigCPtr, this);
  }

  public boolean allowsExtrapolation() {
    return QuantLibJNI.YieldTermStructure_allowsExtrapolation(swigCPtr, this);
  }

}
