/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.vonrosen.quantlib;

public class ZeroInflationIndex extends InflationIndex {
  private transient long swigCPtr;

  protected ZeroInflationIndex(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.ZeroInflationIndex_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ZeroInflationIndex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_ZeroInflationIndex(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ZeroInflationIndex(String familyName, Region region, boolean revised, boolean interpolated, Frequency frequency, Period availabilityLag, Currency currency, ZeroInflationTermStructureHandle h) {
    this(QuantLibJNI.new_ZeroInflationIndex__SWIG_0(familyName, Region.getCPtr(region), region, revised, interpolated, frequency.swigValue(), Period.getCPtr(availabilityLag), availabilityLag, Currency.getCPtr(currency), currency, ZeroInflationTermStructureHandle.getCPtr(h), h), true);
  }

  public ZeroInflationIndex(String familyName, Region region, boolean revised, boolean interpolated, Frequency frequency, Period availabilityLag, Currency currency) {
    this(QuantLibJNI.new_ZeroInflationIndex__SWIG_1(familyName, Region.getCPtr(region), region, revised, interpolated, frequency.swigValue(), Period.getCPtr(availabilityLag), availabilityLag, Currency.getCPtr(currency), currency), true);
  }

}
